name: Go
on: [push]
jobs:

  #lint:
  #  name: Lint
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@master
  #  - uses: grandcolline/golang-github-actions@v1.0.0
  #    with:
  #      run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make build-linux-amd64

    - uses: actions/upload-artifact@master
      with:
        name: dosanco
        path: build

darwin:
  name: Build-darwin
  runs-on: macOS-10.14
  steps:
  - name: Set up Go 1.13
    uses: actions/setup-go@v1
    with:
      go-version: 1.13
    id: go

  - name: Check out code into the Go module directory
    uses: actions/checkout@v1

  - name: Get dependencies
    run: |
      go get -v -t -d ./...

  - name: Build
    run: make build-darwin-amd64

  - uses: actions/upload-artifact@master
    with:
      name: dosanco-darwin
      path: build
