name: Build
on: [push]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - name: lint
      run: make lint

  #build:
  #  name: Build-linux
  #  runs-on: ubuntu-latest
  #  steps:
  #
  #  - name: Set up Go 1.13
  #    uses: actions/setup-go@v1
  #    with:
  #      go-version: 1.13
  #    id: go
  #
  #  - name: Check out code into the Go module directory
  #    uses: actions/checkout@v1
  #
  #  - name: Build
  #    run: make build-linux-amd64
  #
  #  - uses: actions/upload-artifact@master
  #    with:
  #      name: dosanco-linux-amd64
  #      path: build

  #darwin:
  #  name: Build-darwin
  #  runs-on: macOS-10.14
  #  steps:
  #  - name: Set up Go 1.13
  #    uses: actions/setup-go@v1
  #    with:
  #      go-version: 1.13
  #    id: go
  #
  #  - name: Check out code into the Go module directory
  #    uses: actions/checkout@v1
  #
  #  - name: Build
  #    run: make build-darwin-amd64
  #
  #  - uses: actions/upload-artifact@master
  #    with:
  #      name: dosanco-darwin-amd64
  #      path: build

  build:
    name: build
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-10.14]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: make build
    - uses: actions/upload-artifact@master
      with:
        name: dosanco
        path: build